name: Build DEB Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential dpkg-dev g++ 

      - name: Compile project
        run: make

      - name: Create DEB package
        run: |
          mkdir -p usr/bin
          cp word_counter usr/bin/
          mkdir -p DEBIAN
          echo "Package: word-counter
          Version: 1.0
          Section: utils
          Priority: optional
          Architecture: amd64
          Depends: g++, libc6
          Maintainer: Vladiclav4ik
          Description: Программа для подсчёта слов." > deb_package/DEBIAN/control
          dpkg-deb --build deb_package
          mv deb_package.deb word-counter_1.0_amd64.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: word-counter_1.0_amd64.deb
          path: word-counter_1.0_amd64.deb
