name: Build and Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y g++ build-essential

      - name: Compile the project
        run: make

      - name: Verify the binary
        run: usr/bin/word_counter --help || echo "Binary check failed"

      - name: Clean up
        run: make clean

  package:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dpkg-dev
        run: sudo apt update && sudo apt install -y dpkg-dev

      - name: Build the Debian package
        run: |
          mkdir -p package/usr/bin
          cp word_counter package/usr/bin/
          mkdir -p package/DEBIAN
          cp DEBIAN/control package/DEBIAN/
          dpkg-deb --build package word_counter.deb

      - name: Upload Debian package
        uses: actions/upload-artifact@v4

        with:
          name: word_counter-deb
          path: word_counter.deb
